language: python
python:
  - "3.4"
  - "3.3"
  - "2.7"
  - "2.6"
env:
  - DJANGO=1.4.2
  - DJANGO=1.5
  - DJANGO=1.6
  - DJANGO=1.7
  - DJANGO=1.8
  - DJANGO=1.9
  - DJANGO=https://github.com/django/django/archive/master.tar.gz
before_install:
  - pip install -q $DJANGO
install:
  - python setup.py develop
  - pip install -q coveralls
script:
  - coverage run --source=django_su runtests.py
after_success:
  coveralls
matrix:
  exclude:
    - python: "2.6"
      env: DJANGO=1.7
    - python: "2.6"
      env: DJANGO=1.8
    - python: "2.6"
      env: DJANGO=1.9
    - python: "2.6"
      env: DJANGO=https://github.com/django/django/archive/master.tar.gz
    - python: "3.3"
      env: DJANGO=1.4.2
    - python: "3.3"
      env: DJANGO=1.9
    - python: "3.3"
      env: DJANGO=https://github.com/django/django/archive/master.tar.gz
    - python: "3.4"
      env: DJANGO=1.4.2
